PREFERRED_URL_SCHEME: http
ExternalTLSTermination: false
REGISTRY_TITLE: Red Hat Quay
REGISTRY_TITLE_SHORT: Red Hat Quay
DB_CONNECTION_ARGS:
    autorollback: true
    threadlocals: true
DB_URI: postgresql://quayuser:quaypass@${SERVER_HOSTNAME}:5433/quay
BUILDLOGS_REDIS:
    host: ${SERVER_HOSTNAME}
    password: strongpassword
    port: 6379
USER_EVENTS_REDIS:
    host: ${SERVER_HOSTNAME}
    port: 6379
    password: strongpassword
SERVER_HOSTNAME: ${SERVER_HOSTNAME}
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
AUTHENTICATION_TYPE: Database
DATABASE_SECRET_KEY: db_secret_key
SECRET_KEY: secret_key
FEATURE_MAILING: false
SETUP_COMPLETE: true