SERVER_HOSTNAME: <quay-end-point>
PREFERRED_URL_SCHEME: https
FEATURE_UI_V2: true
FEATURE_UI_V2_REPO_SETTINGS: true
FEATURE_AUTO_PRUNE: true
ROBOTS_DISALLOW: false
BROWSER_API_CALLS_XHR_ONLY: false
SUPER_USERS:
  - quay
